---
title: "Longitudinal vs Cross-sectional depRS"
author: "Eileen Xu"
date: "`r Sys.Date()`"
output: 
  html_document:
    toc: true
    toc_depth: 2
    toc_float:
      collapsed: true
editor_options: 
  chunk_output_type: inline
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = F, message = F, results = 'asis')
library(tidyverse)
library(kableExtra)
```

```{r}
long = read.csv("C://Users/eilee/Desktop/PhD/Year 3/envRS/SCRIPTS/OUTPUT/long_coefs.csv")
long = long[-1,-1]
names(long) = c("Predictor", "depRS_long", "intRS_long")
cross = read.csv("C://Users/eilee/Desktop/PhD/Year 3/envRS/SCRIPTS/OUTPUT/base_coefs.csv")
cross = cross[-1,-1]
names(cross) = c("Predictor", "depRS_cross", "intRS_cross")

coefs = merge(long, cross, by = "Predictor")
```

# Predictors for depression problems

```{r}
toplong = coefs[order(abs(coefs$depRS_long), decreasing = T),] |> select(Predictor, depRS_long)
topcross = coefs[order(abs(coefs$depRS_cross), decreasing = T),] |> select(Predictor, depRS_cross)
```


```{r}
toplong[1:10,] |> 
  kable("html", align = 'clc', caption = "Top 10 longitudinal predictors", digits = 3) |> 
    kable_styling(full_width = F, position = "float_left")
 
topcross[1:10,] |> 
  kable("html", align = 'clc', caption = "Top 10 cross-sectional predictors", digits = 3) |> 
    kable_styling(full_width = F, position = "float_right")
```

```{r}
dep = coefs |> select(Predictor, depRS_long, depRS_cross) |> 
  pivot_longer(cols = c("depRS_long", "depRS_cross"), names_to = "model")
dep = dep |> mutate(
  model = case_when(model=="depRS_long" ~ "Longitudinal",
                    model=="depRS_cross" ~ "Cross-sectional")
)

ggplot(dep, aes(x = model, y = Predictor, fill = value)) +
  geom_tile(color = "white", lwd = 1, linetype = 1) +
  geom_text(aes(label = round(value, 3)), color = "black", size = 12, size.unit = "pt") +
  scale_fill_gradient2(name = "Standardised \n Beta", low = "#2166AC", high = "#B2182B") +
  xlab(NULL) + ylab(NULL) +
  theme(panel.grid = element_blank(), panel.background = element_blank(), 
        axis.text = element_text(size = 12), legend.title = element_text(size=12))
```

```{r}
dep_01 = dep |> filter(abs(value)>=0.1)

ggplot(dep_01, aes(x = model, y = Predictor, fill = value)) +
  geom_tile(color = "white", lwd = 1, linetype = 1) +
  geom_text(aes(label = round(value, 3)), color = "black", size = 12, size.unit = "pt") +
  scale_fill_gradient2(name = "Standardised \n Beta", low = "#2166AC", high = "#B2182B") +
  xlab(NULL) + ylab(NULL) +
  theme(panel.grid = element_blank(), panel.background = element_blank(), 
        axis.text = element_text(size = 12), legend.title = element_text(size=12))
```

# Predictors for internalising problems

```{r}
toplong = coefs[order(abs(coefs$intRS_long), decreasing = T),] |> select(Predictor, intRS_long)
topcross = coefs[order(abs(coefs$intRS_cross), decreasing = T),] |> select(Predictor, intRS_cross)
```


```{r}
toplong[1:10,] |> 
  kable("html", align = 'clc', caption = "Top 10 longitudinal predictors", digits = 3) |> 
    kable_styling(full_width = F, position = "float_left")
 
topcross[1:10,] |> 
  kable("html", align = 'clc', caption = "Top 10 cross-sectional predictors", digits = 3) |> 
    kable_styling(full_width = F, position = "right")
```

```{r}
int = coefs |> select(Predictor, intRS_long, intRS_cross) |> 
  pivot_longer(cols = c("intRS_long", "intRS_cross"), names_to = "model")
int = int |> mutate(
  model = case_when(model=="intRS_long" ~ "Longitudinal",
                    model=="intRS_cross" ~ "Cross-sectional")
)

ggplot(int, aes(x = model, y = Predictor, fill = value)) +
  geom_tile(color = "white", lwd = 1, linetype = 1) +
  geom_text(aes(label = round(value, 3)), color = "black", size = 12, size.unit = "pt") +
  scale_fill_gradient2(name = "Standardised \n Beta", low = "#2166AC", high = "#B2182B") +
  xlab(NULL) + ylab(NULL) +
  theme(panel.grid = element_blank(), panel.background = element_blank(), 
        axis.text = element_text(size = 12), legend.title = element_text(size=12))
```

```{r}
int_01 = int |> filter(abs(value)>=0.1)

ggplot(int_01, aes(x = model, y = Predictor, fill = value)) +
  geom_tile(color = "white", lwd = 1, linetype = 1) +
  geom_text(aes(label = round(value, 3)), color = "black", size = 12, size.unit = "pt") +
  scale_fill_gradient2(name = "Standardised \n Beta", low = "#2166AC", high = "#B2182B") +
  xlab(NULL) + ylab(NULL) +
  theme(panel.grid = element_blank(), panel.background = element_blank(), 
        axis.text = element_text(size = 12), legend.title = element_text(size=12))
```